var AlbumConstants = {
  ALL_ALBUMS_RECEIVED: "ALL_ALBUMS_RECEIVED",
  ALBUMS_RECEIVED: "ALBUMS_RECEIVED",
  ALBUM_RECEIVED: "ALBUM_RECEIVED",
  SHOW_ALBUM_RECEIVED: "SHOW_ALBUM_RECEIVED",
  ALBUM_SELECTED: "ALBUM_SELECTED",
  SONG_SELECTED: "SONG_SELECTED",
  PLAY_SWITCHED: "PLAY_SWITCHED"
};

module.exports = AlbumConstants;
